#!/bin/sh

# Just a notification
notify-send -a autorandr "Display configurations changed"

# Get all detected display configurations
x=$(autorandr --detected | sed '/.*autorandr.*/,+d' | sed '/*/,+d')
l=$(echo "$x" | wc -l)
w=$(echo "$x" | wc -w)

# If more than one, make the user choose from rofi menu
if [ $l -gt 1 ];
then
	echo "$x" | rofi -dmenu -p "Display profile: "| xargs autorandr --load
fi

# If no display profiles available, send notification to user to add a
# configuration
if [ $w -eq 0 ];
then
	notify-send -a autorandr "No display profile found" "Please configure how
	you like with for example arandr and then save a profile with autorandr
	--save profilename"
fi
