#!/bin/sh

# Pager

command -v nvim > /dev/null && export MANPAGER='nvim +Man!'

command -v nvim > /dev/null && command -v git > /dev/null &&
	git config --global core.pager "nvim -R" && git config --global color.pager no

# Make vifm exit on current directory

vicd()
{
	local dst="$(command vifm --choose-dir - "$@")"
    	if [ -z "$dst" ]; then
		echo 'Directory picking cancelled/failed'
	return 1
	fi
	cd "$dst"
}
colorTest()
{
	awk -v term_cols="${width:-$(tput cols || echo 80)}" 'BEGIN{
		s="/\\";
		for (colnum = 0; colnum<term_cols; colnum++) {
			r = 255-(colnum*255/term_cols);
			g = (colnum*510/term_cols);
			b = (colnum*255/term_cols);
			if (g>255) g = 510-g;
			printf "\033[48;2;%d;%d;%dm", r,g,b;
			printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
			printf "%s\033[0m", substr(s,colnum%2+1,1);
		}
		printf "\n";
	}'
}

alias doom="~/.emacs.d/bin/doom"
alias pi="ssh -p 2718 pi@crazyminecuber.xyz"
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias svim='vim -u ~/.SpaceVim/vimrc -N'
alias vim="nvim"
alias ll='ls -hlAF --color'
alias ls='ls -hF --color'
alias vifm="vicd"
alias ex="exa --icons -aF --group-directories-first"
alias exl="exa --icons -al --git --group-directories-first"
alias fpacman="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
alias fparu="paru -Slq | fzf --multi --preview 'yay -Si {1}' | xargs -ro yay -S"
alias rm="echo 'You should use \"trash-put\" instead of \"rm\"'"
alias rmdir="echo 'You should use \"trash-put\" instead of \"rmdir\"'"
alias ssh="TERM=xterm-256color ssh"
alias ga="git add"
alias gc="git commit"
alias gs="git status"
alias gd="git diff"
